parallelize: false

stages:
  - name: frcsttrain
    stage: train
    config_files:
      - ./config/era5_o96_forecast.yml
    chain_jobs: 4
    nodes: 2

  - name: operfrcsttrain
    stage: train
    from_run_id: STAGE.frcsttrain
    config_files:
      - ./config/operan_o96_forecast_rollout.yml
    chain_jobs: 2
    nodes: 2